name: Continuous integration for MacOS

on:
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: macos-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        
      - name: Setup .Net 7
        uses: actions/setup-dotnet@v3
        with:
            dotnet-version: '7.x.x'
      
      - name: Restore dependencies
        run: |
          cd src/Asv.Drones.Gui.Desktop
          dotnet workload restore
          dotnet restore

      - name: Build application
        run: |
          cd src/Asv.Drones.Gui.Desktop
          dotnet build -c Release --no-restore

      - name: Upload artifacts
        uses: actions/upload-artifact@v3
        with:
          name: macos-release
          path: ${{ github.workspace }}/src/Asv.Drones.Gui.Desktop/bin/Release/net7.0/
          if-no-files-found: error

      - name: Download artifacts
        uses: actions/download-artifact@v3
        with:
          name: macos-release
          path: macos

            
#  ftps:
#    needs: artifacts
#    runs-on: windows-latest
#    steps:  
#      - uses: actions/download-artifact@v3
#        with:
#          name: windows-release
#          path: windows
#          
#      - name: Sync files with server
#        uses: SamKirkland/FTP-Deploy-Action@4.3.3
#        with:
#            server: ftp.samkirkland.com
#            username: myFtpUserName
#            password: ${{ secrets.FTP_PASSWORD }}
#            protocol: ftps
#            local-dir: ./windows/
#            server-dir: public_html/windows/
#            port: 1234 # todo replace with your web hosts ftps port