# Name of the workflow
name: Release

# Run on every commit tag which begins with "v" (e.g., "v0.1.4")
on:
  push:
    tags:
      - "v*"

# Automatically create a GitHub Release, with release details specified (the relevant commits)
jobs:
  release:
    name: "Release"
    runs-on: "windows-latest"
    
    steps:
      - uses: "asv-soft/action-automatic-release@updated20"
        with:
          repo_token: "${{ secrets.GIHUB_NUGET_AUTH_TOKEN }}" 
          prerelease: false
          files: |
            *Setup.exe
            *.zip
